---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

# Data Science with R– basic 

Durata: 2gg, 8h + 8h

Programma
1.	Introduzione R & RStudio
2.	Le strutture base dei dati, Data Frame
3.	Importare dati
4.	Statistica di base
5.	Manipolare i dati
6.	Visualizzazione dati 
7.	Presentazione dei risultati

# Data Science with R – advance 
Il corso fornisce gli strumenti, i metodi e l'esperienza pratica per sviluppare accurati modelli previsionali, grazie ai quali si crea, all’interno dell’attività aziendale, un migliore processo decisionale e si rendono le tecnologie più intelligenti. I dati possono fornire conoscenze e possono risolvere problemi reali se analizzati con le metodologie di “data science”. Lo scopo del corso è quello di spiegare in modo pratico e intuitivo la statistica, la programmazione e le metodologie di machine learning. 

Durata: 2gg, 8h + 8h

Programma
1.	Introduzione ai metodi di Machine Learning
2.	Tecniche di regressione
3.	Tecniche di classificazione
4.	Riduzione delle dimensioni
5.	Clustering

Il “livello avanzato” richiede la conoscenza di base del linguaggio di programmazione R e i concetti principali delle metodologie in ambito data science che possono essere ascuisite tramite la partecipazione al corso "Data Science with R – basic" 

# Data Science for Smart Factory
Il principale campo di applicazione dove possono essere spese le competenze acquisite in questo corso è nell'ambito Industry 4.0: manutenzione predittiva, IOT analytics, anomaly detection, efficienza energetica, demand forecasting, ottimizzazione e controllo di processo. Le lezioni combinano elementi teorici essenziali con esempi ed applicazioni pratiche su dati reali, illustrative delle varie tecniche, sfruttando il software open source R. 

Programma
1.

Durata: 2gg, 8h + 8h

Il corso richiede la conoscenza di base del linguaggio di programmazione R e i concetti principali delle metodologie in ambito data science che possono essere ascuisite tramite la partecipazione al corso "Data Science with R – basic" 
